### ISSUE TITLE
Avro Functionality

### ISSUE THREAD

**Issue by MojoJojo86** [cswank/kcli#12]
Is it possible to add avro functionality via the use of a plugin like Protobuf?

**Comment by cswank** [comment]
I don't know much about avro, but the protobuf plugin example would be a good template for giving it a shot.  I don't see why not.

**Comment by cswank** [comment]
By the way, I don't have any plans for providing plugins in this repository.  The intent is that they should be easy enough build yourself given the protobuf example.  If you try and get stuck I'll be happy to help you out.
