### ISSUE TITLE
Change name from kcli to kfcli

### ISSUE THREAD

**Issue by jparrill** [cswank/kcli#7]
Hi there,

Any chance to change the app name from _kcli_ to _kfcli_ ? here there is another famous app that already has the same name [kcli](https://github.com/karmab/kcli).

Thanks in advance

**Comment by cswank** [comment]
The k stands for kafka but I am trying to make it work with AWS Kinesis and SQS.  If I can get an SQS interface I would be willing to change it to qcli or something else.  The 'cli' part of the name doesn't even make sense for what this thing does anyhow.
