### ISSUE TITLE
support TLS

### ISSUE THREAD

**Issue by dolfly** [cswank/kcli#8]

**Comment by cswank** [comment]
@dolfly are you talking about TLS authentication like this blog illustrates?

https://medium.com/processone/using-tls-authentication-for-your-go-kafka-client-3c5841f2a625

If so I just pushed a 'tls' branch that uses env vars.  I don't have an easy way to test this but if you would like to check out the branch and try it (this assumes you have a go development environment, if you don't I could build a binary for you):

https://github.com/cswank/kcli/tree/tls

The README in that branch shows the env vars to set to make it work.

**Comment by cswank** [comment]
I merged it to master for v1.5.0 and made a release with the binaries.  Please let me know if it works.
